baseURL = "http://localhost:1313/"
languageCode = "en"
title = "Siddur Sefardi"
theme = "minisiddur"
enableRedirects = true

[params]
  defaultLocationName = "Jerusalem"
  defaultLat = 31.778
  defaultLon = 35.235

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
